<a href="https://colab.research.google.com/github/tuanthex/Pytorch-for-me/blob/main/Matrix_Aggregation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
matrix = torch.tensor([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],])
print(matrix)
print(matrix.sum())
print(matrix.min())
print(matrix.max())
print(matrix.median())
print(matrix.mean())

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor(45.)
tensor(1.)
tensor(9.)
tensor(5.)
tensor(5.)


In [ ]:
print(matrix.min(dim = 0))
print(matrix.max(dim = 0))
print(matrix.sum(dim = 1))

torch.return_types.min(
values=tensor([1., 2., 3.]),
indices=tensor([0, 0, 0]))
torch.return_types.max(
values=tensor([7., 8., 9.]),
indices=tensor([2, 2, 2]))
tensor([ 6., 15., 24.])


In [ ]:
cumulative_sum = matrix.cumsum(dim = 1)
print(cumulative_sum)

tensor([[ 1.,  3.,  6.],
        [ 4.,  9., 15.],
        [ 7., 15., 24.]])


In [ ]:
cumulative_prod = matrix.cumprod(dim = 1)
print(cumulative_prod)

tensor([[  1.,   2.,   6.],
        [  4.,  20., 120.],
        [  7.,  56., 504.]])


In [ ]:
masked_matrix_sum = matrix[matrix > 5].sum()
print(masked_matrix_sum)

tensor(30.)


In [ ]:
matrix2 = matrix.nonzero()
print(matrix2)

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 2],
        [2, 0],
        [2, 1],
        [2, 2]])
